### ISSUE TITLE
Some wheels have different ID and aren't detected by boxflat

### ISSUE THREAD

**Issue by Lawstorant** [Lawstorant/boxflat#11]
CS V2 works with ID of 21 instead of 23

**Comment by NLRevZ** [comment]
Sorry for the soft-hijack here, but how can I verify I am having this issue as well? My brand new ES wheel might have been victim of the same issue; it is not being detected by boxflat but works fine in Pithouse.

**Comment by Lawstorant** [comment]
You can open  `.local/share/flatpak/app/io.github.lawstorant.boxflat/x86_64/stable/active/files/share/boxflat/data/serial.yml`  or `/usr/share/boxflat/data/serial.yml` and change the wheel id in `device-ids` to 21 or 22. Start boxflat again and if your wheel is recognized, it's the same issue.

**Comment by Lawstorant** [comment]
Fixed in v1.14.0

**Comment by Lawstorant** [comment]
@NLRevZ could you report back if this update fixed the detection issue for you?

**Comment by NLRevZ** [comment]
I would, but after updating the app will no longer start. I've tried removing the flatpak and reinstalling it, but no dice.
Running it with -vv shows the following:
```

F: Running '/usr/bin/bwrap --args 37 -- boxflat'
Traceback (most recent call last):
  File "/app/share/boxflat/entrypoint.py", line 3, in <module>
    import boxflat.app as app
  File "/app/share/boxflat/boxflat/app.py", line 5, in <module>
    from boxflat.panels import *
  File "/app/share/boxflat/boxflat/panels/__init__.py", line 1, in <module>
    from .settings_panel import *
  File "/app/share/boxflat/boxflat/panels/settings_panel.py", line 8, in <module>
    from boxflat.connection_manager import MozaConnectionManager
  File "/app/share/boxflat/boxflat/connection_manager.py", line 502
    print(f"New id: {self._serial_data["device-ids"]["wheel"]}")
                                        ^^^^^^
SyntaxError: f-string: unmatched '['
```

**Comment by Lawstorant** [comment]
@NLRevZ yeah sorry. I released a version that works native but has some issues when packaged. Fortunately, hotfix is already up on Flathub and I can confirm it's working this time :D

**Comment by NLRevZ** [comment]
You're right, the ES wheel now detects just fine and the RPM LEDs work fine as well.

**Comment by Lawstorant** [comment]
Great to hear.
Closing.
