### ISSUE TITLE
Adding preset configs

### ISSUE THREAD

**Issue by NLRevZ** [Lawstorant/boxflat#15]
With different games sometimes requiring dramatically different (mostly wheelbase) settings, I find myself having to write down the correct settings for each game.
Is saving / applying configs a planned feature for boxflat?

**Comment by Lawstorant** [comment]
Yes, I do want to create a preset system based on yaml files. Maybe even loading PitHouse presets. I don't know when I'll be work on such feature, but that's on my radar. Let's leave this issue open.

Beyond that, I'll se if I can implement per-game presets that could load automatically.

**Comment by Lawstorant** [comment]
@NLRevZ 
Here's a screen form a pretty complete implementation of Boxflat presets. What do you think?
![image](https://github.com/user-attachments/assets/f22bdd7d-ac65-4ef4-866e-0106691106cf)
