### ISSUE TITLE
Moza ES Wheel No Longer Connecting

### ISSUE THREAD

**Issue by OPNightMarine** [Lawstorant/boxflat#18]
Since update 1.16.8 or 1.17.0 my wheel is no longer detected in boxflat. It was connecting versions before hand, I think Python3 had an update not 100% though nothing else was updated before the issue to my knowledge. Since the issue I reinstalled boxflat and updated the universal-pidff. As well as running the update too see if any required apps were outdated. I also tried manual install, the app wouldn't even boot. I also checked on a closed issue where changing the wheel id from 23 to 22 or 21, no luck there.

System -
Pop!_OS jammy 22.04 x86_64
Linux 6.9.3-76060903-generic
GNOME 42.9
Mutter (X11)

Wheel -
Moza R5 Es Wheel with sr-p lite pedals

App - 
Current version - 1.17.2
Installed through flatpack

I don't know what other details would be useful.

Much appreciated,
- OPNightMarine

**Comment by Lawstorant** [comment]
Thanks for opening this issue. ES Wheel support is indeed spotty as I don't own it and it behaves slightly different from other wheels. I'll see if I broken something regarding the ID searching.

**Comment by Lawstorant** [comment]
@OPNightMarine could you check out the [18-moza-r5-es-wheel-no-longer-connecting](https://github.com/Lawstorant/boxflat/tree/18-moza-r5-es-wheel-no-longer-connecting) branch? It might fix the detection again

**Comment by OPNightMarine** [comment]
> Thanks for opening this issue. ES Wheel support is indeed spotty as I don't own it and it behaves slightly different from other wheels. I'll see if I broken something regarding the ID searching.
> 
> Any updates to python etc won't matter as the flatpak version is sandboxed form the rest of the system. It relies on it's own python binaries provided by flatpak.

That's interesting, why would the es wheel act differently then the others. Thanks for looking into it.

**Comment by OPNightMarine** [comment]
> @OPNightMarine could you check out the [18-moza-r5-es-wheel-no-longer-connecting](https://github.com/Lawstorant/boxflat/tree/18-moza-r5-es-wheel-no-longer-connecting) branch? It might fix the detection again

Can do

**Comment by OPNightMarine** [comment]
@Lawstorant When booting up the app it doesn't load and returns with. AttributeError: 'gi.repository.Gtk' object has no attribute 'ColorDialogButton'

Full Log -

Traceback (most recent call last):
  File "/usr/share/boxflat/entrypoint.py", line 3, in <module>
    import boxflat.app as app
  File "/usr/share/boxflat/boxflat/app.py", line 5, in <module>
    from boxflat.panels import *
  File "/usr/share/boxflat/boxflat/panels/__init__.py", line 1, in <module>
    from .settings_panel import *
  File "/usr/share/boxflat/boxflat/panels/settings_panel.py", line 1, in <module>
    from boxflat.widgets import *
  File "/usr/share/boxflat/boxflat/widgets/__init__.py", line 11, in <module>
    from .new_color_picker_row import *
  File "/usr/share/boxflat/boxflat/widgets/new_color_picker_row.py", line 14, in <module>
    class BoxflatNewColorPickerRow(BoxflatRow):
  File "/usr/share/boxflat/boxflat/widgets/new_color_picker_row.py", line 65, in BoxflatNewColorPickerRow
    def _notify(self, button: Gtk.ColorDialogButton, param) -> None:
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'ColorDialogButton'

**Comment by Lawstorant** [comment]
Anywho, I updated the wheel detection command and version v1.17.4 will be up on flathub in about 3 hours

**Comment by OPNightMarine** [comment]
> Anywho, I updated the wheel detection command and version v1.17.4 will be up on flathub in about 3 hours

Much appreciated.

**Comment by OPNightMarine** [comment]
@Lawstorant I was able to find out that pop os 22.04 doesn't have the lastest versions anymore. Only 24.04 does. So until that's updated or i can manual install, boxflat will no longer work. Apologies not able to find this until now.

**Comment by Lawstorant** [comment]
Yeah, no problem. You'll still be able to use it from flathub though

**Comment by OPNightMarine** [comment]
> Yeah, no problem. You'll still be able to use it from flathub though

Yup the app will load but I won't be able to use it. Hopefully your fix works. Otherwise I'ma have to install 24.04. I appreciate the help.

**Comment by Lawstorant** [comment]
Just to make sure. Is it only the ES wheel that's not detected or everything? Base, pedals and wheel?

**Comment by OPNightMarine** [comment]
> Just to make sure. Is it only the ES wheel that's not detected or everything? Base, pedals and wheel?

Seems like everything isn't detected.
