### ISSUE TITLE
Moza ES Wheel No Longer Connecting Continued

### ISSUE THREAD

**Issue by OPNightMarine** [Lawstorant/boxflat#21]
Since the issue was closed

I installed ubuntu 24.04. The base now connects as well as the pedals, now just the wheel doesn't connect. Tried the wheel ID thing again, still no connection.

**Comment by Lawstorant** [comment]
Is it possible that you haven't updated the firmware in a while? Currently, boxflat development follows newest formware versions and I still haven't figured out how to check the firmware version on the devices.

**Comment by Lawstorant** [comment]
Because honestly, I don't know why it wouldn't work. Do you at least see the values change in the wheel section eve if it's still disabled?

**Comment by OPNightMarine** [comment]
> Is it possible that you haven't updated the firmware in a while? Currently, boxflat development follows newest formware versions and I still haven't figured out how to check the firmware version on the devices.

That's why I installed the lastest Ubuntu 24.04 from pop os 22.04

**Comment by OPNightMarine** [comment]
> Because honestly, I don't know why it wouldn't work. Do you at least see the values change in the wheel section eve if it's still disabled?

Yes switches from ID 23 to ID 21

**Comment by Lawstorant** [comment]
> > Is it possible that you haven't updated the firmware in a while? Currently, boxflat development follows newest formware versions and I still haven't figured out how to check the firmware version on the devices.
> 
> That's why I installed the lastest Ubuntu 24.04 from pop os 22.04

I meant the wheel firmware. You need windows and PitHouse to update that

**Comment by OPNightMarine** [comment]
> > > Is it possible that you haven't updated the firmware in a while? Currently, boxflat development follows newest formware versions and I still haven't figured out how to check the firmware version on the devices.
> > 
> > 
> > That's why I installed the lastest Ubuntu 24.04 from pop os 22.04
> 
> I meant the wheel firmware. You need windows and PitHouse to update that

Unless they updated in the last week then yes. I'll check when I can. Didn't know the firmware crossed over os's.

**Comment by OPNightMarine** [comment]
@Lawstorant Ok I've got some info. Went to windows, firmware was up to date, pithouse needed an update so I updated it in case. Went to Ubuntu, base and pedels still connect but the wheel still doesn't. I booted into pop os, found there was a kernel update. After updating I tried connecting, when Boxflat loaded the No Udev rules box appeared, at the same time I noticed that my base connected sadly didn't think to check the wheel. After added the Udev rules I rebooted and started Boxflat. Now it's back too not detecting my base. I will try removing the Udev rules an see what happens there.

**Comment by OPNightMarine** [comment]
Think I found the issue. It's something in the Udev rules, I can now use my wheel and race. Only problem now is I can't edit any settings in Boxflat. Hope this helps.

**Comment by OPNightMarine** [comment]
Forgot to add, this is for both pop os 22.04 and ubuntu 24.04.

**Comment by Lawstorant** [comment]
@OPNightMarine could you join our linux simracing community in matrix? I'd want to debug this with you more real-time and afterwards we will update this thread to contain the findings

https://matrix.to/#/#simracing:matrix.org

**Comment by OPNightMarine** [comment]
> @OPNightMarine could you join our linux simracing community in matrix? I'd want to debug this with you more real-time and afterwards we will update this thread to contain the findings
> 
> https://matrix.to/#/#simracing:matrix.org

When I can, sure thing. Never heard of Matrix Sim Racing before.

**Comment by OPNightMarine** [comment]
@Lawstorant I'm having issues connecting. I'm pretty sure I'm connecting right, Server - #simracing:matrix.org with my own name and password. From what I'm seeing this is a sweet app, just wish it was working for me.

**Comment by Lawstorant** [comment]
Hmm, I'm using my github account to log into Element.

I still don't see a reason why your ES wheel wouldn't be detected but I'm going to create a new branch for you that will tell us a little bit more of what's appening behind the scenes ok?

**Comment by Lawstorant** [comment]
I was debugging the ES wheel with someone else on Matrix. I'll ask them if it works for them

**Comment by NLRevZ** [comment]
Just to make a formal reply here: I too am having this same issue. Just updated Boxflat and it stopped seeing the ES wheel.

**Comment by Lawstorant** [comment]
We did a live session with @NLRevZ and ES wheel detection should be fixed in v1.18.3

This version will be available on flathub in few hours. Please report if this version fixes this issue for you @OPNightMarine

**Comment by OPNightMarine** [comment]
> Hmm, I'm using my github account to log into Element.
> 
> I still don't see a reason why your ES wheel wouldn't be detected but I'm going to create a new branch for you that will tell us a little bit more of what's appening behind the scenes ok?

No clue, sounds good.

**Comment by OPNightMarine** [comment]
> We did a live session with @NLRevZ and ES wheel detection should be fixed in v1.18.3
> 
> This version will be available on flathub in few hours. Please report if this version fixes this issue for you @OPNightMarine

When I have it I'll let ya know.

**Comment by OPNightMarine** [comment]
@Lawstorant With version 1.18.3 the UDev Rules are still breaking the connection to the base and wheel. I'll continue trying to connect to matrix in the meantime.

**Comment by Lawstorant** [comment]
Something else must be broken on your end. Did you restart your system? It seems like there might be another instance of boxflat running and it's messing up the serial connection. That or you are running Monocoque. Sadly, serial connections are exclusive so Monocoque and Boxflat interfere with each other

**Comment by Lawstorant** [comment]
The issue was resolved and any further issues are due to configuration/something interfering with serial connection.

**Comment by Lawstorant** [comment]
@OPNightMarine this new version might actually fix your issue. I'll let you know when it's released.

**Comment by OPNightMarine** [comment]
For info its random which update breaks the connection. The fix I've been using is either removing or adding the udev rules, depending on the update, one or the other works. Note without the udev rules you have to set the settings from either your phone or moza pit house on windows.

**Comment by Lawstorant** [comment]
My apologies. I don't have the ES wheel on hand so can't test it.

**Comment by Lawstorant** [comment]
@OPNightMarine new version is now live on Flathub. You might want to give it a spin. It'll be great if this finally fixes the ES wheel for you (remember to wait a bit for detection)

**Comment by OPNightMarine** [comment]
> @OPNightMarine new version is now live on Flathub. You might want to give it a spin. It'll be great if this finally fixes the ES wheel for you (remember to wait a bit for detection)

Its now back to being broken, after the 1.19.7 update.

**Comment by Lawstorant** [comment]
@OPNightMarine could you give me the output of `ls -lah /dev/ | grep ACM`?

**Comment by OPNightMarine** [comment]
@Lawstorant Both versions 1.19.7 and 1.20.0 returned crw-rw-rw-   1 root  dialout 166,     0 Oct 14 16:12 ttyACM0

1.20.0 is working with udev rules.

**Comment by Lawstorant** [comment]
Yeah, the file mode is affected by the UDEV rule, not the application itself. Still, good to know that it's finally working for you.

Buuut 1.20.0 didn't change anything when it comes to device detection/communications, so still weird it didn't work before.

I hope I won't break it anymore :D

**Comment by OPNightMarine** [comment]
> Yeah, the file mode is affected by the UDEV rule, not the application itself. Still, good to know that it's finally working for you.
> 
> Buuut 1.20.0 didn't change anything when it comes to device detection/communications, so still weird it didn't work before.
> 
> I hope I won't break it anymore :D

For sure, its quite weird, if I get any other clues I'll let ya know. Same here would definitely be nice.
