### ISSUE TITLE
Please add 2520 mark to base rotation

### ISSUE THREAD

**Issue by writequit** [Lawstorant/boxflat#23]
First thanks for this program, I'm using a Moza R12 and it works great. 

Small QOL request, ATS has maximum animation range of 2520 so it's nice to have a mark at that point. I added it myself to base.py and it just works.

After upgrading from a G29 I get a bit of a kick from having 7 turns lock to lock :)

**Comment by Lawstorant** [comment]
Sure.You could create a PR for this change if you would want to be in the commit history. Just FYI

**Comment by Lawstorant** [comment]
And as far as turning goes, I don't know the limit yet, but I was able to set a rotation limit of 40 000. Yes, over 100 turns lock to lock :D
