### ISSUE TITLE
Steering axis position display wrong

### ISSUE THREAD

**Issue by NLRevZ** [Lawstorant/boxflat#25]
In the Base tab, if my wheelbase is centered the visual representation at the top of the window (to the right of 'Important settings') is filled all the way to the left. 
If I turn the wheel all the way to the right the visual representation indicates the wheel is centered. 
If I steer all the way to the left the bar goes beyond the limit by another 100% of its intended length.

The wheel itself works fine in games, I think it's just the visual in Boxflat that's going awry.
![Screenshot_20240922_135252](https://github.com/user-attachments/assets/e9c7ba6f-129c-448c-b03e-a84791e598a4)

**Comment by Lawstorant** [comment]
May I ask which version is that?

**Comment by NLRevZ** [comment]
Hey, I didn't notice the rotation being weird on the home screen as well. Center is -450° and full right is 0°.
This morning I updated it to v1.18.0-flatpak and this issue started occurring (along with the other issue of the ES wheel not detecting anymore).

**Comment by Lawstorant** [comment]
And what's your base?

Could you send me the output of `evtest /dev/input/by-id/*MOZA*`? I don't really need the whole log of events, just the info it shows after starting it

**Comment by NLRevZ** [comment]
It's an R9 V2 wheelbase, and I haven't touched the firmware since I first started using it about a month ago.
I was just driving in ACC and it shows just fine in there as it has always been:
![Screenshot_20240922_151646](https://github.com/user-attachments/assets/e9cae6da-09d6-4811-baed-50feec44cba2)

evtest gives me the following (also, no Fuzz or Flat values in ABS_X):
`
Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    -11
      Min   -32768
      Max    32767`

**Comment by Lawstorant** [comment]
Ok, thanks. Seems like the issue is how this is handled in old vs new firmware. I recommend just updating o the new FFB 3.0 algorithm, but I'll try detecting this automatically

**Comment by NLRevZ** [comment]
Your notion has proven to be correct. Updating to 1.2.3.13 has changed the values so that the scale reported is 0-65535 and the graphic in Boxflat acts properly now. Still, dynamic handling of the scale could prove useful.
