### ISSUE TITLE
Flathub armv7 build

### ISSUE THREAD

**Issue by danhultg** [Lawstorant/boxflat#31]
I want to use this on a Raspberry Pi 3b, unfortunately there doesn't seem to be any build on Flathub for that. Is it possible to add?

**Comment by Lawstorant** [comment]
Unfortunately, I'm not in charge of Flathub's build infrastructure. I'm not gating any platforms, but it doesn't seem like they are building for 32bit ARM anymore.

What I could do, id to share info on how to build flatpak package on your own system.

**Comment by Lawstorant** [comment]
As per this [Issue](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1105), Armv7 is no longer supported.
