### ISSUE TITLE
ES Wheel not connecting

### ISSUE THREAD

**Issue by TimSchmock** [Lawstorant/boxflat#33]
Hi, 
I have a similar issue to the one OPNightMarine had a few weeks ago. My R5 Base and my srp-lite pedals connect to boxflat, but my ES Wheel doesn't. I'm on a clean Arch install right now, I've tried the flatpak and the aur version, I've also tried the flatpak on Fedora 40, but no luck. A few weeks back it worked for a little bit, but I wasn't actively using the wheel so I unfortunately don't know when it broke. I am on the newest Base firmware 1.2.2.15, I've also tried downgrading to 1.2.2.11, I believe it was, in the pit House software. I have also seen this https://github.com/Lawstorant/boxflat/issues/21#issuecomment-2371476515 but I really don't know what could be interfering. So I really don't know what to do. 
Thanks in advance,
Lukas

**Comment by Lawstorant** [comment]
With the amount of issues the ES wheel is giving me, I might as well just buy it to have it on hand for testing. I don't even know what I'm breaking with every other update. Well, let me look at it and maybe I'll whip up a test version for you.

**Comment by Lawstorant** [comment]
Oh, and one more thing. @TimSchmock could you provide me Boxflat version that you tried?

**Comment by Lawstorant** [comment]
Okay, you can get the testing version from the https://github.com/Lawstorant/boxflat/tree/es-test branch.

**Comment by TimSchmock** [comment]
Oh wow thanks for the fast response! The ES Wheel really sounds annoying to work with.
unfortunately, it still doesn't work with the es-test branch, I don't get any output with any of the IDs and commands, the terminal just shows this: 

Cycling wheel id. New id: 24
Cycling wheel id. New id: 23
Cycling wheel id. New id: 22
Cycling wheel id. New id: 21
Cycling wheel id. New id: 20

and some gdk warnings.

the Version I tried was 1.19.5, so just the newest release.

**Comment by Lawstorant** [comment]
The newest one is 1.19.6

**Comment by TimSchmock** [comment]
It is 1.19.6, I must have misread, sorry 
yes, i tried all 4 with every ID. Yes it should be on the newest version:
![Screenshot 2024-10-11 133914](https://github.com/user-attachments/assets/2a0db055-357c-41b2-823c-b3f31f5ec72d)
I don't think it is one with Xbox compatibility, but afaik the rev leds show which mode it is in, and pulsating should be PC mode.

**Comment by Lawstorant** [comment]
Oh, okay, I think I know what is the problem

**Comment by TimSchmock** [comment]
Now it's cycling IDs 21-23: but still no connection to the wheel. I've tried the four commands again and still no return-values.

**Comment by Lawstorant** [comment]
Okay, I updated the branch again. This time it will log if there's any data coming from the wheel. You should cycle the ID to `21` as this is where it previously worked

**Comment by TimSchmock** [comment]
Well, still nothing. It doesn't look like the wheel is sending anything. It should print "wheel data received", right?

**Comment by Lawstorant** [comment]
@TimSchmock I updated the branch yet again. Now it only sends out wheel commands.
You still must cycle the ID yourself, but I made the possible range even bigger. IF this won't work, I'm out of ideas and maybe I'll send you a modified OLDER version, which will show us what does this wheel really outputs.

I know the sending part must be working, because the wheel worked before. The only thing back then was that I didn't do any processing of the responses, because I did have async IO. I just took the first thing that came out of the device after sending the command.

**Comment by TimSchmock** [comment]
It's working! With wheel ID 19 it works! So maybe my wheel was just out of range of our earlier tests?

**Comment by Lawstorant** [comment]
Ok, thanks. One last update, could you update the branch one last time and just see if it works with id of 18 as well?

And now, I have to rethink how to approach this. Could you send me some of the console outputs? I want to see the device id from the response

**Comment by TimSchmock** [comment]
Yes, it works with 18 as well. 

Sure: 
Writing: 7e:03:28:13:01:00:01:cb
Received: 7e:03:a8:31:01:01:c2
Received: 7e:05:0e:21:03:00:2a:00:01
Received: 7e:05:0e:21:03:00:9d:00:01
Received: 7e:02:c0:21:04:01

if you need more this is a longer part:
[log.txt](https://github.com/user-attachments/files/17346530/log.txt)

**Comment by Lawstorant** [comment]
Thanks, I'll be able to go from there 

It's weird as it seems like it somehow works with base ids, but that doesn't work with my RS V2, nor GS V2P. Is your base/wheel a bit older? Like from 2022 maybe when moza still did wireless wheels?

It being wireless is my only guess as to why it's working this way.

**Comment by TimSchmock** [comment]
No, I bought it in March this Year. But that really is weird, maybe they changed something in the newer Firmware?

**Comment by Lawstorant** [comment]
Well, I guess I'll find out when it fomes to my wheels as well :D

I'll let you know when I'll have a fix ready for you to test

**Comment by TimSchmock** [comment]
Yeah, thank you!

**Comment by Lawstorant** [comment]
@TimSchmock you can try the `final-es-fix` branch now.

**Comment by TimSchmock** [comment]
I've tried it and it seems like it is indeed working. Thanks :)
