### ISSUE TITLE
Moza ES and R3 detection issues

### ISSUE THREAD

**Issue by AlexAtHome** [Lawstorant/boxflat#40]
### Affected version:

- v1.22.2-flatpak
- v1.22.2

### Current Behavior:

The app does not detect the steering wheel (Moza ES) and the base (R3), but it does detect the pedals.
I can change the throttle curve and range, reverse direction for both throttle and break pedals. Not sure if the calibration works.
Everything is detected properly in Moza Pit House on Windows and in Moza app on Android.
The wheel is properly detected by Firefox in Gamepad Tester, and it does work in ATS (both Proton and native), FH5, and Motor Town.
I tried to update the firmware from 1.2.2.17 to 1.2.3.14, tries the branch from #27, tried tinkering with id detection of the wheel in `serial.yml` (#11). Nothing made Boxflat detect my devices.

**Comment by Lawstorant** [comment]
Hi!
So it seems this is strictly a base issue as wheels are detected through the wheelbase. If your wheelbase isn't detected, your wheel won't be. Moza devices present two USB devices. A HID joystick for input and a serial connection for settings/telemetry. It's the latter that has issues in this case. Looking at how your pedals are actually detected (I presume they are connected with USB directly?), udev rules must be installed on your system.

Could you run boxflat from terminal and post the little logging it has right now? It should at least tell us if it detects the base at all and just errors out immediately .

One more thing. Is the ES wheel the "normal" variant or the xbox one?

**Comment by Lawstorant** [comment]
Oh, and maybe `ls -lah /dev/serial/by-id` as well.

**Comment by AlexAtHome** [comment]
> I presume they are connected with USB directly

They are connected to the wheelbase.

> udev rules must be installed on your system

They are.
```
λ ~/ cat /etc/udev/rules.d/99-boxflat.rules
# Copyright (c) 2024, Tomasz Pakuła Using Arch BTW

# Add uaccess tag to every Moza (Gudsen) ttyACM device so a user can easily access it
# without being added to the uucp group. This in turn will make it so EVERY user
# can access these devices
SUBSYSTEM=="tty", KERNEL=="ttyACM*", ATTRS{idVendor}=="346e", ACTION=="add", MODE="0666", TAG+="uaccess"
```

> Could you run boxflat from terminal and post the little logging it has right now?

```
λ ~/ flatpak run io.github.lawstorant.boxflat 
"pedals" connected
```
This is literally the whole output. And a bunch of Gsk-Warnings when I clicked "About".

> `ls`

```
λ ~/ /bin/ls -lah /dev | grep ttyACM
crw-rw-rw-+  1 root uucp      166,     0 Nov  1 13:17 ttyACM0
λ ~/ /bin/ls -lah /dev/serial/by-id 
total 0
drwxr-xr-x 2 root root 60 Nov  1 12:58 .
drwxr-xr-x 4 root root 80 Nov  1 12:58 ..
lrwxrwxrwx 1 root root 13 Nov  1 12:58 usb-Gudsen_R3_Racing_Wheel_and_Pedals_470028001351333033333434-if00 -> ../../ttyACM0
```

> Is the ES wheel the "normal" variant or the xbox one?

It's an Xbox one

**Comment by Lawstorant** [comment]
Okay, seems like a simple thing. The R3 seems to have a different name, not included in my filters. I'll get on it.

In the meantime, could you make sure your Xbox ES rim is running in PC mode?

**Comment by Lawstorant** [comment]
![372635461-3c4444bf-737a-4c9f-ab30-f155266765ef](https://github.com/user-attachments/assets/c421d610-11cb-40c2-9580-42c590de194a)

**Comment by AlexAtHome** [comment]
Okay, I'll try doing that later today

I should've suspected that it could have two modes

**Comment by Lawstorant** [comment]
Ok, thanks. I know what the problem is then. Your base is recognized as pedals

**Comment by AlexAtHome** [comment]
> Your base is recognized as pedals

Oh, right, I completely forgot to mention it. If I unplug the pedals from the base, it still says in the logs `"pedals" connected`

> Could you post the output...
```
λ ~/ /bin/ls -lah /dev/input/by-id
total 0
drwxr-xr-x 2 root root 240 Nov  1 18:57 .
drwxr-xr-x 4 root root 580 Nov  1 18:57 ..
lrwxrwxrwx 1 root root   9 Nov  1 18:40 usb-COOLERMASTER_ARGB_Box_A201804091608-if01-event-kbd -> ../event6
lrwxrwxrwx 1 root root   9 Nov  1 18:57 usb-Gudsen_R3_Racing_Wheel_and_Pedals_470028001351333033333434-if02-event-joystick -> ../event3
lrwxrwxrwx 1 root root   6 Nov  1 18:57 usb-Gudsen_R3_Racing_Wheel_and_Pedals_470028001351333033333434-if02-joystick -> ../js0
lrwxrwxrwx 1 root root   9 Nov  1 18:40 usb-Logitech_USB_Receiver-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Nov  1 18:40 usb-Logitech_USB_Receiver-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root   9 Nov  1 18:40 usb-Logitech_USB_Receiver-mouse -> ../mouse1
lrwxrwxrwx 1 root root   9 Nov  1 18:40 usb-SEMITEK_USB-HID_Gaming_Keyboard_SN0000000001-event-kbd -> ../event2
lrwxrwxrwx 1 root root   9 Nov  1 18:40 usb-SEMITEK_USB-HID_Gaming_Keyboard_SN0000000001-if02-event-mouse -> ../event4
lrwxrwxrwx 1 root root   9 Nov  1 18:40 usb-SEMITEK_USB-HID_Gaming_Keyboard_SN0000000001-if02-mouse -> ../mouse0
lrwxrwxrwx 1 root root  10 Nov  1 18:40 usb-SteelSeries_Arctis_Nova_7X-event-if04 -> ../event21
```

**Comment by Lawstorant** [comment]
Fix pushed to master

**Comment by AlexAtHome** [comment]
Just tried Boxflat from `main` branch. Now everything is detected properly

Thank you very much
