### ISSUE TITLE
All widgets quickly become inactive

### ISSUE THREAD

**Issue by iphands** [Lawstorant/boxflat#51]
Loving the work!! The custom driver works so well. I want to play Horizon 5 though and need to flip on the compat mode in boxflat.

Im using the flatpak option and as soon as I launch I see all the widgets, and then after 0.5s they go grey (become inactive).
I see no console messages :(

### Affected version:
v1.25.3-flatpak

### Are your devices running the latest firmware?:
Yes. Updated FW in Windows yesterday.

### Current Behavior:
Loving the work!! The custom driver (JacKeTUs/universal-pidff) works so well.
I want to play Horizon 5 though and need to flip on the compat mode in boxflat.

Im using the flatpak option and as soon as I launch I see all the widgets, and then after 0.5s they go grey (become inactive).
I see no console messages :(

### Expected Behavior:
Expect to see some console message about an error or non disabled widgets (ie can use).

### Steps To Reproduce:
1. Open Boxflat
2. Try to click on any widget
3. Fail because they are all diabled

**Comment by iphands** [comment]
![1734237888](https://github.com/user-attachments/assets/6077e253-0455-4190-a0a9-309eb421f1f9)
![1734238059](https://github.com/user-attachments/assets/963e74b4-d8b2-4dc4-a42c-edee3266c4c3)

**Comment by iphands** [comment]
Oh I noticed that the code looks up a serial device that I dont have!
```
$ ls -lh /dev/input/by-id/*MOZA*
lrwxrwxrwx 1 root root 10 Dec 14 22:00 /dev/input/by-id/usb-Gudsen_MOZA_R5_Base_410028000651303334393332-if02-event-joystick -> ../event13

$ ls -lh /dev/serial
ls: cannot access '/dev/serial': No such file or directory
```

Any idea what driver makes the serial device?

**Comment by iphands** [comment]
Im pretty user the missing driver is cdc_acm ie `USB Modem (CDC ACM) support ` in kernel menuconfig.

**Comment by iphands** [comment]
Yay! It works! Thanks @Lawstorant for the awesome software!

**Comment by Lawstorant** [comment]
Seems like I could att thos to the requirements list.

Just to make sure, what distro are you running? I never had to configure this manually.

Oh, and as far as the compatibility mode goes, I don't think it does anything on Linux. It just changes the device PID. There are some dll files that pithouse injects on Windows that you would have to source.

**Comment by iphands** [comment]
> Seems like I could att thos to the requirements list.

I can make a PR if youd like

> Just to make sure, what distro are you running? I never had to configure this manually.

Lol... "Using Gentoo BTW". Any major distro probably builds that module by default.

> Oh, and as far as the compatibility mode goes, I don't think it does anything on Linux. It just changes the device PID. There are some dll files that pithouse injects on Windows that you would have to source.

Ahh lame! I am trying it out now. I might try and switch to FH4 though :(
You know if anyone has done a deep dive into what is going on there yet?

**Comment by Lawstorant** [comment]
Well, what's hoing on is that Forza Horizon had absolutely terrible FFB support and even with DLL files from PitHouse, it barely works.

I have a windows VM, I could maybe get the needed files

**Comment by iphands** [comment]
Hey do you know how to track down the DLLs properly?
Im toying with the Moza Pithouse app in wine and see only these
```
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/WRC 9 FIA World Rally Championship/Plugins/PhysXCooking64_s.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/WRC 9 FIA World Rally Championship/Plugins/PhysXCooking64_s_org.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/WRC 8 FIA World Rally Championship/Plugins/PhysXCooking64_s.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/WRC 8 FIA World Rally Championship/Plugins/PhysXCooking64_s_org.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/WRC 10 FIA World Rally Championship/Plugins/PhysXCooking64_s.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/WRC 10 FIA World Rally Championship/Plugins/PhysXCooking64_s_org.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/rFactor 2/Plugins/rF2SharedMemeryMapPlugin.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/rFactor 2/Plugins/rFactor2SharedMemoryMapPlugin64.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/Le Mans Ultimate/Plugins/InternalsPlugin.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/Le Mans Ultimate/Plugins/rF2SharedMemeryMapPlugin.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/Le Mans Ultimate/Plugins/rFactor2SharedMemoryMapPlugin64.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/Euro Truck Simulator 2/plugins/ETS2SharedMemoryMapPlugin32.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/Euro Truck Simulator 2/plugins/ETS2SharedMemoryMapPlugin64.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/American Truck Simulator/plugins/atssharedpluginx64.dll
./pfx/drive_c/Program Files (x86)/MOZA Pit House/GameConfigs/American Truck Simulator/plugins/atssharedpluginx86.dll
```

Nothing there is related to Horizon I think

**Comment by Lawstorant** [comment]
You know what? I actually have a Windows VM to play EA WRC. I'll just install FH5 and see what it applies. I could send these files for you then. Maybe even include them in this repo
