### ISSUE TITLE
It's not available on Flathub

### ISSUE THREAD

**Issue by Primake** [Lawstorant/boxflat#7]
I get a 404 when I use the link in the README.md: https://flathub.org/apps/io.github.lawstorant.boxflat

**Comment by Lawstorant** [comment]
Yeah, sorry. I was a bit too eager and updated the README a bit too early. It has been accepted and I'm waiting for them to publish it.

Once again, sorry for the confusion

**Comment by Lawstorant** [comment]
https://github.com/flathub/flathub/pull/5460
This is the blocker for now. It should be merged in the coming days

**Comment by Lawstorant** [comment]
@Primake boxflat is not available on FlatHub! https://flathub.org/apps/io.github.lawstorant.boxflat
